package:
  name: collectd
  version: 5.12.0
  epoch: 0
  description: "The system statistics collection daemon."
  copyright:
    - license: MIT

# NOTE: Commented out packages are ones we don't have today in wolfi
#
# Thus list also uses the alpine package for comparison. HOWEVER there are a lot
# of 'optional' packages listed in the pre-reqisites section of the git repo
# docs which alpine has choosen not to include.
#
# QUESTION: Assume we do the same here and mirror what alpine has done?
#
# References:
# - https://git.alpinelinux.org/aports/tree/community/collectd/APKBUILD#n13
# - https://github.com/collectd/collectd/blob/main/README.md
# - https://www.collectd.org/download.html#source
environment:
  contents:
    packages:
      - autoconf
      - automake
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl-dev
      - eudev-dev
      - flex
      - gpsd-dev
      - hiredis-dev
      - i2c-tools-dev
      - iptables-dev
      - jansson-dev
      - libatasmart-dev
      - libdbi-dev
      - libgcrypt-dev
      - libmemcached-dev
      - libmicrohttpd-dev
      - libmnl-dev
      - libmodbus-dev
      - libnotify-dev
      - liboping-dev
      - libpcap-dev
      - libpq-16 # We have libpq-15, is this the same?
      - librdkafka-dev
      - libtool
      - libxml2-dev
      - lm-sensors-dev
      - lua5.3-dev
      - mariadb-connector-c-dev
      - mosquitto-dev
      - net-snmp-dev
      - openipmi-dev
      - openldap-dev
      - openssl-dev>3
      - owfs-dev
      - patchelf
      - perl-dev
      - pkgconf
      - pkgconf-dev
      - python3-dev
      - rabbitmq-c
      - rabbitmq-c-dev
      - riemann-c-client-dev
      - rrdtool-dev
      - varnish
      - yajl-dev
      - zlib-dev
      - openjdk-17-default-jdk
      - postgresql-16-dev
      - gdk-pixbuf-dev
      - mariadb-dev
      - pango-dev
      - harfbuzz-dev
      - cairo-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/collectd/collectd.git
      tag: collectd-${{package.version}}
      expected-commit: 3f935d017e81b7eaf84c9df421490230845dc5c0

  - uses: patch
    with:
      patches: fix-cross-compilation.patch


  - runs: |
      # As per 'generating the configure script' in docs
      # - https://github.com/collectd/collectd/blob/main/README.md
      ./build.sh

      if "${{build.arch}}" == "x86_64"; then
        _flags="--disable-turbostat"
      elif "${{build.arch}}" == "aarch64"; then
        _flags="--disable-java"
      fi

      # Configure options, copied from:
      # - https://git.alpinelinux.org/aports/tree/community/collectd/APKBUILD#n13
      ./configure \
        --build=$CBUILD \
        --host=$CHOST \
        --prefix=/usr \
        --sysconfdir=/etc/collectd \
        --mandir=/usr/share/man \
        --infodir=/usr/share/info \
        --localstate=/var \
        --with-libiptc \
        --disable-werror \
        --with-perl-bindings=INSTALLDIRS=vendor \
        --with-java=/usr/lib/jvm/default-jvm \
        \
        --enable-all-plugins \
        --disable-amqp1 \
        --disable-apple_sensors \
        --disable-aquaero \
        --disable-dcpmm \
        --disable-dpdkevents \
        --disable-dpdkstat \
        --disable-dpdk_telemetry \
        --disable-gmond \
        --disable-gpu_nvidia \
        --disable-grpc \
        --disable-intel_pmu \
        --disable-intel_rdt \
        --disable-ipstats \
        --disable-lpar \
        --disable-mic \
        --disable-netapp \
        --disable-netlink \
        --disable-netstat_udp \
        --disable-notify_email \
        --disable-nut \
        --disable-oracle \
        --disable-pf \
        --disable-redfish \
        --disable-routeros \
        --disable-sigrok \
        --disable-slurm \
        --disable-tape \
        --disable-tokyotyrant \
        --disable-write_mongodb \
        --disable-write_prometheus \
        --disable-xencpu \
        --disable-xmms \
        --disable-virt \
        --disable-pinba \
        --disable-barometer \
        --disable-capabilities \
        --disable-turbostat \
        --disable-write_riemann \
        --disable-ping \
        --disable-zone \
        $_flags

        make

        make DESTDIR="${{targets.destdir}}" install
        find "${{targets.destdir}}" \( -name perllocal.pod -o -name .packlist \) -delete


        mkdir -p "${{targets.destdir}}"/etc/collectd.d
        mkdir -p "${{targets.destdir}}"/etc/init.d
        mkdir -p "${{targets.destdir}}"/usr/include/collectd/core
        mkdir -p "${{targets.destdir}}"/usr/include/collectd/liboconfig

        install -D -m755 ./${{package.name}}.initd "${{targets.destdir}}"/etc/init.d/${{package.name}}

         # Install all header files to allow building out-of-tree plugins.
         # This is based on Debian.
         for path in $(find src -path src/libcollectdclient -prune \
         	-o -path src/liboconfig -prune \
         	-o -name '*.h' -print)
         do
         	install -D -m644 "$path" "${{targets.destdir}}"/usr/include/collectd/core/${path#src/}
         done

        install -D -m644 ./src/liboconfig/oconfig.h -t "${{targets.destdir}}"/usr/include/collectd/liboconfig/
        cd "${{targets.destdir}}"/usr/include/collectd/
        # Update include path for collectd core header files.
        headers=$(find ./core ./liboconfig -type f -name '*.h')
        for path in $headers; do
        	sed -r -i "s|(include\s+)\".*\<${path##*/}\"|\1\"collectd/${path#./}\"|" $headers
        done

  - uses: strip

update:
  enabled: true
  github:
    identifier: collectd/collectd
    strip-prefix: collectd-
