package:
  name: collectd
  version: 5.12.0
  epoch: 0
  description: "The system statistics collection daemon."
  copyright:
    - license: MIT

# NOTE: Commented out packages are ones we don't have today in wolfi
#
# Thus list also uses the alpine package for comparison. HOWEVER there are a lot
# of 'optional' packages listed in the pre-reqisites section of the git repo
# docs which alpine has choosen not to include.
#
# QUESTION: Assume we do the same here and mirror what alpine has done?
#
# References:
# - https://git.alpinelinux.org/aports/tree/community/collectd/APKBUILD#n13
# - https://github.com/collectd/collectd/blob/main/README.md
# - https://www.collectd.org/download.html#source
environment:
  contents:
    packages:
      - autoconf
      - automake
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl-dev
      - eudev-dev
      - flex
      # - gpsd-dev
      - hiredis-dev
      # - i2c-tools-dev
      - iptables-dev
      - jansson-dev
      - libatasmart-dev
      - libdbi-dev
      - libgcrypt-dev
      # - libmemcached-dev
      # - libmicrohttpd-dev
      - libmnl-dev
      # - libmodbus-dev
      - libnotify-dev
      # - liboping-dev
      - libpcap-dev
      # - libpq-dev # We have libpq-15, is this the same?
      - librdkafka-dev
      - libtool
      - libxml2-dev
      # - lm-sensors-dev
      # - lua-dev
      - mariadb-connector-c-dev
      - mosquitto-dev
      # - net-snmp-dev
      # - openipmi-dev 
      - openldap-dev
      - openssl-dev>3
      # - owfs-dev
      - patchelf
      - perl-dev
      - pkgconf
      - pkgconf-dev
      - python3-dev
      - rabbitmq-c
      - rabbitmq-c-dev
      # - riemann-c-client-dev
      # - rrdtool-dev
      # - varnish-dev # We have non-dev package, is this the same?
      - yajl-dev
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/collectd/collectd.git
      tag: collectd-${{package.version}}
      expected-commit: 3f935d017e81b7eaf84c9df421490230845dc5c0

  - runs: |
      # As per 'generating the configure script' in docs
      # - https://github.com/collectd/collectd/blob/main/README.md
      ./build.sh

      # Configure options, copied from:
      # - https://git.alpinelinux.org/aports/tree/community/collectd/APKBUILD#n13
      ./configure \
        --build=$CBUILD \
        --host=$CHOST \
        --prefix=/usr \
        --sysconfdir=/etc/collectd \
        --mandir=/usr/share/man \
        --infodir=/usr/share/info \
        --localstate=/var \
        --with-libiptc \
        --disable-werror \
        --with-perl-bindings=INSTALLDIRS=vendor \
        --with-java=/usr/lib/jvm/default-jvm \
        \
        --enable-all-plugins \
        --disable-amqp1 \
        --disable-apple_sensors \
        --disable-aquaero \
        --disable-dcpmm \
        --disable-dpdkevents \
        --disable-dpdkstat \
        --disable-dpdk_telemetry \
        --disable-gmond \
        --disable-gpu_nvidia \
        --disable-grpc \
        --disable-intel_pmu \
        --disable-intel_rdt \
        --disable-ipstats \
        --disable-lpar \
        --disable-mic \
        --disable-netapp \
        --disable-netlink \
        --disable-netstat_udp \
        --disable-notify_email \
        --disable-nut \
        --disable-oracle \
        --disable-pf \
        --disable-redfish \
        --disable-routeros \
        --disable-sigrok \
        --disable-slurm \
        --disable-tape \
        --disable-tokyotyrant \
        --disable-write_mongodb \
        --disable-write_prometheus \
        --disable-xencpu \
        --disable-xmms \
        --disable-zone

      make
      make install DESTDIR="${{targets.destdir}}"

update:
  enabled: true
  github:
    identifier: collectd/collectd


