package:
  name: openipmi
  version: 2.0.34
  epoch: 0
  description: IPMI (Intelligent Platform Management Interface) library and tools
  copyright:
    - license: LGPL-2.0-or-later and GPL-2.0-or-later or BSD-3-Clause

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - glib-dev
      - libedit-dev
      - linux-headers
      - ncurses-dev
      - net-snmp-dev
      - openssl-dev
      - popt-dev
      - readline-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 93227e43c72b5c3bd5949323e0669aa5527d1a971473a3a365af03fb8284a95f
      uri: https://downloads.sourceforge.net/openipmi/OpenIPMI-${{package.version}}.tar.gz

  - uses: autoconf/configure
    with:
      opts: |
        --disable-static \
        --with-ucdsnmp \
        --without-python

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: openipmi-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - openipmi
    description: openipmi dev

  - name: openipmi-doc
    pipeline:
      - uses: split/manpages
    description: openipmi manpages

  - name: openipmi-lanserv
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/etc "${{targets.subpkgdir}}"/
          mv "${{targets.destdir}}"/usr/lib/libIPMIlanserv.so.* "${{targets.subpkgdir}}"/usr/lib/
          mv "${{targets.destdir}}"/usr/bin/ipmilan \
          	"${{targets.destdir}}"/usr/bin/ipmi_sim \
          	"${{targets.destdir}}"/usr/bin/sdrcomp \
          	"${{targets.subpkgdir}}"/usr/bin/
    description: Emulates an IPMI network listener

update:
  enabled: true
  release-monitor:
    identifier: 2549
